### ISSUE TITLE
how i can use this in laravel

### ISSUE THREAD

**Issue by vahidalvandi** [tarek-aec/elastix-api#11]
hi
please help me how i can use this in laravel?

**Comment by 101t** [comment]
Unfortunately, you cannot use it with Laravel, it only works with Elastix Server with PHP4

**Comment by vahidalvandi** [comment]
i will install laravel in Elastix Server  , and i need just get api call from Elastix ..

**Comment by 101t** [comment]
make sure you have installed two php 4 for elasitx api and lavavel php >= 7.2  versions on server
