### ISSUE TITLE
Generate Token Key

### ISSUE THREAD

**Issue by yogiprayoga049** [tarek-aec/elastix-api#3]
I am sory Iam new in elastix... I want know where is or which one menu in elastix to generate token key ? Thanks

**Comment by 101t** [comment]
Hi,
This api server is not elastix plugin or it is not related to generator, **elastix does not have http api**, and this api service designed to be **http api**, so the key you want to generat it could be any e.g 50 random characters or it could be any size you want [Password Generator link](https://www.lastpass.com/password-generator), also you could store it manually in `api.php` to secure api usage between elastix and your app, I will write small document to help people to use it very well.

**Comment by yogiprayoga049** [comment]
Hi,
Oke tarek-aec... thank's for the explanation...

**Comment by TharHtetWai** [comment]
Hi, When I generate the token and replace to api.php and access from web browser.but I see only "test" result. any reference for this. appreciate for you idea.Thanks.
![image](https://user-images.githubusercontent.com/47787475/59581334-8b9c2280-90fa-11e9-8247-63c1750e3f08.png)

**Comment by 101t** [comment]
@TharHtetWai  you could not access api from browser immediatelly because `GET` method not allowed only `POST` method, so you need to use API Client tester such as **Postman** [Postman](https://www.getpostman.com/downloads/).

**Comment by TharHtetWai** [comment]
Hi, my idea is create API and to collect the operator panel information and show with new webapp. I'm stuck at the API stage and any idea? appreciate for your suggestions.

**Comment by 101t** [comment]
@TharHtetWai you can start from [this document](https://github.com/101t/elastix-api/wiki/Elastix-API-Document) so if you have any question you could share it here.

**Comment by TharHtetWai** [comment]
Hi, when i try to GET CDR report and key not found error. sorry for too much request.I'm newbi in API and developing. I'm just System Engineer.Please see the screenshot.

![image](https://user-images.githubusercontent.com/47787475/59592831-d1ff7a80-9116-11e9-8774-934ffee7a8bb.png)

**Comment by 101t** [comment]
Please check the header content must be like:
```http
POST /api/api.php HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: kJBJzUqZ2W9THvW9vrFTEzXN7NNfDv9XyzENAn7teWDsZCcYHj
```

![ewrwerewrew](https://user-images.githubusercontent.com/4958477/59598341-a378a400-9104-11e9-9b2a-731ce054ba43.png)

**Comment by TharHtetWai** [comment]
Thanks. I will try again.
