### ISSUE TITLE
Security fix main/elastix.php

### ISSUE THREAD

**Issue by cmfrtl** [tarek-aec/elastix-api#6]
main/elastix.php

public function get_wav_file() - can take ../../../../../etc/passwd and any readable file
i check path before open file:

$name           = $_GET["name"];
$directory      = "/var/spool/asterisk/monitor";
$file = realpath($directory . $name);
if(strpos($file, $directory) !== false && strpos($file, $directory) == 0 && file_exists($file) && is_file($file)){

**Comment by 101t** [comment]
it is fixed, thanks.
