### ISSUE TITLE
CDR report endpoint Empty Body

### ISSUE THREAD

**Issue by evanxg852000** [tarek-aec/elastix-api#9]
The CDR report endpoint returns empty body even with the Elastix dashboard having a lot of data in cdr report. All the other endpoints work properly.
I tried using a combination of the filters without any luck

**Comment by 101t** [comment]
It's a CDR API that supports JSON format only, you may read more about it [here](https://github.com/101t/elastix-api/wiki/Elastix-API-Document#get-cdr-report)

**Comment by evanxg852000** [comment]
Well,  I know it's an API. and I have setup the api on our Elatix server the other endpoint return data.
But when I do an api request on  `https://server.com/api/api.php?cmd=cdrreport` nothing comes back.
The response body is `empty` content size: `0`.
Is this normal knowing I can see the data in the dashboard
?
The json response is empty; I mean no data at all  
I am testing with:
`curl --header "Authorization: xxxxxx" https://x.x.x.x/api/api.php?cmd= cdrreport`
Again the other endpoints work well

**Comment by 101t** [comment]
May I ask a question, have you installed `elastix-api` very well?

**Comment by evanxg852000** [comment]
The json response is empty; I mean no data at all
I am testing with:
curl --header "Authorization: xxxxxx" https://x.x.x.x/api/api.php?cmd= cdrreport
Again the other endpoints work well

`activecall` command for instance returns data.

This makes me believe that the api is installed properly

**Comment by 101t** [comment]
could you make sure that:
```sh
curl -X POST https://x.x.x.x/api/api.php?cmd=cdrreport \
     -H 'Authorization: xxxxxx' \
     -H 'Content-Type:application/x-www-form-urlencoded'
```

**Comment by evanxg852000** [comment]
I actually just posted a portion of the cURL. even using your's it's still the same. the following is the response headers coming from your command above

```
curl -k -i -X POST https://x.x.x.x/api/api.php\?cmd=cdrreport \
     -H 'Authorization: secret' \
     -H 'Content-Type:application/x-www-form-urlencoded'
```

```HTTP/1.1 200 OK
Date: Mon, 25 Mar 2019 11:32:46 GMT
Server: Apache/2.2.3 (CentOS)
X-Powered-By: PHP/5.1.6
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8
```

but I just noticed it's trying to send back `text/html` instead of `application/json` .
I also tried using Postman.
Thank you for the support by the way 👍

**Comment by 101t** [comment]
Very nice, I suggest to use `postman` as REST API tester.

**Comment by evanxg852000** [comment]
I will debug since I have a PHP knowledge and let you know.

**Comment by evanxg852000** [comment]
Hi, I had to recover my access to the Elastix server since. I have been able to fix the API endpoint issue. I have also made a pull request  https://github.com/101t/elastix-api/pull/10 
Please review once you have time.

**Comment by 101t** [comment]
I think it needs to test, before merge commit
Also, I want to mention that If you have 100,000 of cdr data record it will be a problem to load a lot of data so `startdate` and `enddate` is required as date range in sql query.

**Comment by evanxg852000** [comment]
yes sure, of course. Just let me know on this thread if anything is wrong. Thank you for this tool it saves a lot of energy 👍 .

**Comment by 101t** [comment]
#10 You're welcome, your pull request has been confirmed.
